### ISSUE TITLE
TM16xxDisplay.h compilation error under Linux

### ISSUE THREAD

**Issue by RanTalbott** [maxint-rd/TM16xx#3]
Thanks very much for doing and sharing this. Especially for for the Adafruit GFX integration: I've been using that for OLED and LCD displays, so it'll be really nice to be able to use it for the matrix LEDs I just bought.

At line 20 of TM16xxDisplay.h you include <print.h>, but it's not found under Linux because filenames are case-sensitive. Changing it to <Print.h> got rid of the error.

**Comment by maxint-rd** [comment]
Fixed. Thank you Ran!
(Obviously I didn't test compiling under Linux. It probably also failed under MacOS)
