### ISSUE TITLE
TM1650.h compilation error

### ISSUE THREAD

**Issue by RanTalbott** [maxint-rd/TM16xx#4]
Found under Arduino 1.8.4, compiling for Wemos D1 mini. I was actually compiling TM16xxMatrixGFX_Ticker.ino for a TM1640 display, but the IDE wanted to build everything it found in the library's src directory:

In file included from /root/Arduino/libraries/TM16xx-master/src/TM1650.cpp:12:0:
/root/Arduino/libraries/TM16xx-master/src/TM1650.h:49:18: error: extra qualification 'TM1650::' on member 'receive' [-fpermissive]
     virtual byte TM1650::receive();
                  ^
exit status 1
Error compiling for board WeMos D1 R2 & mini.

Changing the line to:
    virtual byte receive();

eliminated the error message. It _should_ have no effect on function, but I have no way to test, since I don't have any TM1650 devices.

**Comment by maxint-rd** [comment]
Fixed. Thank you Ran!
(Don't know why my version of the IDE didn't complain)
