### ISSUE TITLE
how we can use 4 segment with dot

### ISSUE THREAD

**Issue by harymk** [maxint-rd/TM16xx#40]
am building a clock how can i use centre dp ":" on tm1628

``#include <TM1628.h>
#include <TM16xxDisplay.h>

TM1628 module(11, 10, 9);   // DIO=8, CLK=9, STB=7
#define NUM_DIGITS 5
TM16xxDisplay display(&module, NUM_DIGITS); 

void setup() {
       
       display.print("10:30");
}

void loop() {
  // put your main code here, to run repeatedly:

}
``

![Schematic_328 +1628_2023-09-03](https://github.com/maxint-rd/TM16xx/assets/40994861/958d9ffa-ccce-4271-9e94-e38aab296633)

**Comment by maxint-rd** [comment]
Hello Hari, you closed this issue as completed. Does that mean that you found a solution?

(My first thought was that it depends on the LED display that you're using. I have a LED display with colon between second and third digit and dots after each digit. It's a bit weird sins first dot isn't connected. When that DP line is used, it lights up the colon. The second dot is connected, but third and forth aren't connected either.)
