### ISSUE TITLE
include Library into the Arduino Library Manager

### ISSUE THREAD

**Issue by SkullKill** [maxint-rd/TM16xx#8]
might be a good idea to include it into the Arduino Library Manager?

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by maxint-rd** [comment]
Good suggestion. Thanks! I'm not sure when I find the time, but I will put this on my todo-list.

**Comment by SkullKill** [comment]
p.s made this esp32 wall clock which uses the TM1638 in anode mode, with 10 Segment/digits. will try to get this to work with this library when the board comes and i have some time to solder all the components in. 

will post the design files for the board etc on github once done.

![ESP32-Wall-Clock-Front-RT-V1 0](https://user-images.githubusercontent.com/20982257/90456785-68b93400-e12c-11ea-90bc-7eb817e3cd5c.jpg)


![ESP32-Wall-Clock-Front-BoardOnly-V1 0](https://user-images.githubusercontent.com/20982257/90456823-7f5f8b00-e12c-11ea-9074-9608b5d2ef3c.jpg)

![ESP32-Wall-Clock-Back-V1 0](https://user-images.githubusercontent.com/20982257/90456831-84bcd580-e12c-11ea-8997-700ab8c2714a.jpg)

**Comment by SkullKill** [comment]
got this to work for 10 digits, 8 segment, in common anode mode. 

pull request submitted 

https://github.com/maxint-rd/TM16xx/pull/9


TM1638 in Common Anode mode, 10 Digits, 8 Segment

for schematics of 1st digit connected to SEG1, 2nd digit connected to SEG2 of TM1638 etc....

Schemathics of Anode connection available here https://github.com/SkullKill/ESP32-Wall-Clock-PCB and https://github.com/SkullKill/ESP32-Wall-Clock-PCB/wiki

did not modify the TM1638QYF.h module because, it looks like this has an inverted connection for the digits , i.e 1st digit connected to SEG8, 2nd digit connected to SEG7 etc...

![ESP32-Wall-Clock-01](https://user-images.githubusercontent.com/20982257/91472748-7dcf5900-e8ca-11ea-94a5-eaf7d5e16aec.jpg)


![ESP32-Wall-Clock-schematics-03-V1 0](https://user-images.githubusercontent.com/20982257/91472777-8758c100-e8ca-11ea-8089-1743855edaef.jpg)
